name: dungeon_run
description: A Flame game template built with Flutter.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.18.0
  audioplayers: ^6.0.0
  flame_audio: ^2.10.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  nes_ui: ^0.20.0
  google_fonts: ^6.2.0
  logging: ^1.2.0
  fluttertoast: ^8.2.12
  toastification: ^3.0.2
  rive: ^0.13.20
  flame_rive: ^1.10.15
  rive_splash_screen: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flame_test: ^1.16.2
  test: ^1.25.0
  flutter_lints: ^5.0.0
  lints: ^5.1.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/characters/
    - assets/images/enemies/
    - assets/images/scenery/
    - assets/images/attacks/
    - assets/images/traps/
    - assets/images/collectables/
    - assets/music/
    - assets/sfx/
    - assets/animations/

  fonts:
    - family: Press Start 2P
      fonts:
        - asset: assets/fonts/Press_Start_2P/PressStart2P-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
