import 'package:dungeon_run/flame_game/components/characters/character_type.dart';
import 'package:dungeon_run/flame_game/components/collectables/collectable_type.dart';
import 'package:dungeon_run/store/upgrade.dart';

/// List that store the starting situation of upgrades
final List<Upgrade> defaultUpgrades = [
  (
    name: "warrior",
    description: "Guerriero",
    subMenu: 0,
    unlocked: true,
    dependency: null,
    characterType: CharacterType.warrior,
    collectableType: null,
    cost: 0,
    costFactor: 0,
    currentLevel: 0,
    maxLevel: 0,
    baseCooldown: null,
    step: null,
  ),
  (
    name: "warrior_life",
    description: "Vita",
    subMenu: 1,
    unlocked: null,
    dependency: "warrior",
    characterType: null,
    collectableType: null,
    cost: 20,
    costFactor: 1.5,
    currentLevel: 0,
    maxLevel: 10,
    baseCooldown: null,
    step: 10.0,
  ),
  (
    name: "warrior_damage",
    description: "Danni",
    subMenu: 1,
    unlocked: null,
    dependency: "warrior",
    characterType: null,
    collectableType: null,
    cost: 20,
    costFactor: 1.5,
    currentLevel: 0,
    maxLevel: 10,
    baseCooldown: null,
    step: 5.0,
  ),
  (
    name: "warrior_special",
    description: "Attacco speciale",
    subMenu: 1,
    unlocked: null,
    dependency: "warrior",
    characterType: null,
    collectableType: null,
    cost: 50,
    costFactor: 1.5,
    currentLevel: 0,
    maxLevel: 5,
    baseCooldown: 5,
    step: 0.5,
  ),
  (
    name: "archer",
    description: "Arciere",
    subMenu: 0,
    unlocked: false,
    dependency: null,
    characterType: CharacterType.archer,
    collectableType: null,
    cost: 0,
    costFactor: 0,
    currentLevel: 0,
    maxLevel: 0,
    baseCooldown: null,
    step: null,
  ),
  (
    name: "archer_life",
    description: "Vita",
    subMenu: 1,
    unlocked: null,
    dependency: "archer",
    characterType: null,
    collectableType: null,
    cost: 20,
    costFactor: 1.5,
    currentLevel: 0,
    maxLevel: 10,
    baseCooldown: null,
    step: 5.0,
  ),
  (
    name: "archer_damage",
    description: "Danni",
    subMenu: 1,
    unlocked: null,
    dependency: "archer",
    characterType: null,
    collectableType: null,
    cost: 20,
    costFactor: 1.5,
    currentLevel: 0,
    maxLevel: 10,
    baseCooldown: null,
    step: 3.0,
  ),
  (
    name: "archer_special",
    description: "Attacco speciale",
    subMenu: 1,
    unlocked: null,
    dependency: "archer",
    characterType: null,
    collectableType: null,
    cost: 50,
    costFactor: 1.5,
    currentLevel: 0,
    maxLevel: 5,
    baseCooldown: 5,
    step: 0.5,
  ),
  (
    name: "mage",
    description: "Mago",
    subMenu: 0,
    unlocked: false,
    dependency: null,
    characterType: CharacterType.mage,
    collectableType: null,
    cost: 0,
    costFactor: 0,
    currentLevel: 0,
    maxLevel: 0,
    baseCooldown: null,
    step: null,
  ),
  (
    name: "mage_life",
    description: "Vita",
    subMenu: 1,
    unlocked: null,
    dependency: "mage",
    characterType: null,
    collectableType: null,
    cost: 20,
    costFactor: 1.5,
    currentLevel: 0,
    maxLevel: 10,
    baseCooldown: null,
    step: 5.0,
  ),
  (
    name: "mage_damage",
    description: "Danni",
    subMenu: 1,
    unlocked: null,
    dependency: "mage",
    characterType: null,
    collectableType: null,
    cost: 20,
    costFactor: 1.5,
    currentLevel: 0,
    maxLevel: 10,
    baseCooldown: null,
    step: 2.0,
  ),
  (
    name: "mage_special",
    description: "Attacco speciale",
    subMenu: 1,
    unlocked: null,
    dependency: "mage",
    characterType: null,
    collectableType: null,
    cost: 50,
    costFactor: 1.5,
    currentLevel: 0,
    maxLevel: 5,
    baseCooldown: 5,
    step: 0.5,
  ),
  (
    name: "assassin",
    description: "Assassino",
    subMenu: 0,
    unlocked: false,
    dependency: null,
    characterType: CharacterType.assassin,
    collectableType: null,
    cost: 0,
    costFactor: 0,
    currentLevel: 0,
    maxLevel: 0,
    baseCooldown: null,
    step: null,
  ),
  (
    name: "assassin_life",
    description: "Vita",
    subMenu: 1,
    unlocked: null,
    dependency: "assassin",
    characterType: null,
    collectableType: null,
    cost: 20,
    costFactor: 1.5,
    currentLevel: 0,
    maxLevel: 10,
    baseCooldown: null,
    step: 3.0,
  ),
  (
    name: "assassin_damage",
    description: "Danni",
    subMenu: 1,
    unlocked: null,
    dependency: "assassin",
    characterType: null,
    collectableType: null,
    cost: 20,
    costFactor: 1.5,
    currentLevel: 0,
    maxLevel: 10,
    baseCooldown: null,
    step: 2.0,
  ),
  (
    name: "assassin_special",
    description: "Attacco speciale",
    subMenu: 1,
    unlocked: null,
    dependency: "assassin",
    characterType: null,
    collectableType: null,
    cost: 50,
    costFactor: 1.5,
    currentLevel: 0,
    maxLevel: 5,
    baseCooldown: 5,
    step: 0.5,
  ),
  (
    name: "berserk",
    description: "Berserk",
    subMenu: 0,
    unlocked: false,
    dependency: null,
    characterType: CharacterType.berserk,
    collectableType: null,
    cost: 0,
    costFactor: 0,
    currentLevel: 0,
    maxLevel: 0,
    baseCooldown: null,
    step: null,
  ),
  (
    name: "berserk_life",
    description: "Vita",
    subMenu: 1,
    unlocked: null,
    dependency: "berserk",
    characterType: null,
    collectableType: null,
    cost: 20,
    costFactor: 1.5,
    currentLevel: 0,
    maxLevel: 10,
    baseCooldown: null,
    step: 10.0,
  ),
  (
    name: "berserk_damage",
    description: "Danni",
    subMenu: 1,
    unlocked: null,
    dependency: "berserk",
    characterType: null,
    collectableType: null,
    cost: 20,
    costFactor: 1.5,
    currentLevel: 0,
    maxLevel: 10,
    baseCooldown: null,
    step: 4.0,
  ),
  (
    name: "berserk_special",
    description: "Attacco speciale",
    subMenu: 1,
    unlocked: null,
    dependency: "berserk",
    characterType: null,
    collectableType: null,
    cost: 50,
    costFactor: 1.5,
    currentLevel: 0,
    maxLevel: 5,
    baseCooldown: 5,
    step: 0.5,
  ),
  (
    name: "collectable",
    description: "Collezionabili",
    subMenu: 0,
    unlocked: null,
    dependency: null,
    characterType: null,
    collectableType: null,
    cost: 0,
    costFactor: 0.0,
    currentLevel: 0,
    maxLevel: 0,
    baseCooldown: null,
    step: null,
  ),
  (
    name: "collectable_heal",
    description: "Cura",
    subMenu: 1,
    unlocked: true,
    dependency: null,
    characterType: null,
    collectableType: CollectableType.heal,
    cost: 0,
    costFactor: 0.0,
    currentLevel: 0,
    maxLevel: 0,
    baseCooldown: null,
    step: null,
  ),
  (
    name: "augment_heal",
    description: "Aumento cura",
    subMenu: 2,
    unlocked: null,
    dependency: "collectable_heal",
    characterType: null,
    collectableType: null,
    cost: 50,
    costFactor: 1.5,
    currentLevel: 0,
    maxLevel: 10,
    baseCooldown: null,
    step: 3.0,
  ),
  (
    name: "collectable_damage",
    description: "Danno",
    subMenu: 1,
    unlocked: false,
    dependency: null,
    characterType: null,
    collectableType: CollectableType.damage,
    cost: 0,
    costFactor: 0.0,
    currentLevel: 0,
    maxLevel: 0,
    baseCooldown: null,
    step: null,
  ),
  (
    name: "augment_damage",
    description: "Aumento danno",
    subMenu: 2,
    unlocked: null,
    dependency: "collectable_damage",
    characterType: null,
    collectableType: null,
    cost: 50,
    costFactor: 1.5,
    currentLevel: 0,
    maxLevel: 10,
    baseCooldown: null,
    step: 0.5,
  ),
  (
    name: "augment_damage_duration",
    description: "Aumento durata danno",
    subMenu: 2,
    unlocked: null,
    dependency: "collectable_damage",
    characterType: null,
    collectableType: null,
    cost: 50,
    costFactor: 1.5,
    currentLevel: 0,
    maxLevel: 5,
    baseCooldown: null,
    step: 2.0,
  ),
  (
    name: "collectable_slow",
    description: "Rallentamento",
    subMenu: 1,
    unlocked: false,
    dependency: null,
    characterType: null,
    collectableType: CollectableType.slow,
    cost: 0,
    costFactor: 0.0,
    currentLevel: 0,
    maxLevel: 0,
    baseCooldown: null,
    step: null,
  ),
  (
    name: "augment_slow",
    description: "Aumento rallentamento",
    subMenu: 2,
    unlocked: null,
    dependency: "collectable_slow",
    characterType: null,
    collectableType: null,
    cost: 50,
    costFactor: 1.5,
    currentLevel: 0,
    maxLevel: 5,
    baseCooldown: null,
    step: 1.0,
  ),
  (
    name: "augment_slow_duration",
    description: "Aumento durata rallentamento",
    subMenu: 2,
    unlocked: null,
    dependency: "collectable_slow",
    characterType: null,
    collectableType: null,
    cost: 50,
    costFactor: 1.5,
    currentLevel: 0,
    maxLevel: 5,
    baseCooldown: null,
    step: 2.0,
  ),
  (
    name: "collectable_invincibility",
    description: "Invincibilità",
    subMenu: 1,
    unlocked: false,
    dependency: null,
    characterType: null,
    collectableType: CollectableType.invincibility,
    cost: 0,
    costFactor: 0.0,
    currentLevel: 0,
    maxLevel: 0,
    baseCooldown: null,
    step: null,
  ),
  (
    name: "augment_invincibility_duration",
    description: "Aumento durata invincibilità",
    subMenu: 2,
    unlocked: null,
    dependency: "collectable_invincibility",
    characterType: null,
    collectableType: null,
    cost: 50,
    costFactor: 1.5,
    currentLevel: 0,
    maxLevel: 5,
    baseCooldown: null,
    step: 2.0,
  ),
  (
    name: "collectable_resurrection",
    description: "Resurrezione",
    subMenu: 1,
    unlocked: false,
    dependency: null,
    characterType: null,
    collectableType: CollectableType.resurrection,
    cost: 0,
    costFactor: 0.0,
    currentLevel: 0,
    maxLevel: 0,
    baseCooldown: null,
    step: null,
  ),
  (
    name: "augment_resurrection",
    description: "Aumento vita post resurrezione",
    subMenu: 2,
    unlocked: null,
    dependency: "collectable_resurrection",
    characterType: null,
    collectableType: null,
    cost: 50,
    costFactor: 1.5,
    currentLevel: 0,
    maxLevel: 1,
    baseCooldown: null,
    step: null,
  ),
  (
    name: "collectable_frequency",
    description: "Aumento frequenza collezionabili",
    subMenu: 1,
    unlocked: true,
    dependency: null,
    characterType: null,
    collectableType: null,
    cost: 50,
    costFactor: 1.5,
    currentLevel: 0,
    maxLevel: 5,
    baseCooldown: null,
    step: null,
  ),
  (
    name: "enemy_gold",
    description: "Aumento soldi dei nemici",
    subMenu: 0,
    unlocked: true,
    dependency: null,
    characterType: null,
    collectableType: null,
    cost: 50,
    costFactor: 1.5,
    currentLevel: 0,
    maxLevel: 10,
    baseCooldown: null,
    step: null,
  ),
];
